version: '3.7'

services:

  tp_link_router_exporter:
    container_name: tp_link_router_exporter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://host.docker.internal:3133/api/v1/health || exit 1" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "2003:2003"
      - "1805:1805"
    environment:
      # like `10.0.1.1` or `tplinkwifi.net`
      - TP_LINK_ROUTER_IP=${TP_LINK_ROUTER_IP}
      # like `admin` or `jordan`
      - TP_LINK_ROUTER_USERNAME=${TP_LINK_ROUTER_USERNAME}
      # hopefully something secret!
      - TP_LINK_ROUTER_PASSWORD=${TP_LINK_ROUTER_PASSWORD}
    stdin_open: true
    tty: true
