version: '3.7'

services:

  tp_link_router_exporter:
    container_name: tp_link_router_exporter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://host.docker.internal:3133/api/v1/health || exit 1" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./exporter_config.yaml:/etc/tp_link_exporter/exporter_config.yaml
    ports:
      - "3133:3133"
      - "9233:9233"
    environment:
      # like `http://10.0.1.1` or `http://tplinkwifi.net`
      - TP_LINK_ROUTER_IP=${TP_LINK_ROUTER_IP}
      # this you can make up to be whatever you want, like `Living Room Router`
      - TP_LINK_ROUTER_NAME=${TP_LINK_ROUTER_NAME}
      # hopefully something secret!
      - TP_LINK_ROUTER_PASSWORD=${TP_LINK_ROUTER_PASSWORD}
      # TODO: clean up when I have better implementation
      - TP_LINK_ROUTER_IP_2=${TP_LINK_ROUTER_IP_2}
      # hopefully something secret!
      - TP_LINK_ROUTER_PASSWORD_2=${TP_LINK_ROUTER_PASSWORD_2}
      - TP_LINK_ROUTER_NAME_2=${TP_LINK_ROUTER_NAME_2}
    stdin_open: true
    tty: true
